import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ReduxProvider from '@/providers/redux-provider'
import { Toaster } from "react-hot-toast"
import ClientProvider from '@/providers/query-client-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProvider>
          <ReduxProvider>
            <Toaster />
            {children}
          </ReduxProvider>
        </ClientProvider>
      </body>
    </html>
  )
}
